FROM node:20-alpine
WORKDIR /app

# Yarn clásico determinístico
RUN corepack enable && corepack prepare yarn@1.22.22 --activate

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 5173
CMD ["yarn", "dev", "--host"]