services:
  web:
    build:
      context: ..                 # raíz del proyecto
      dockerfile: docker/Dockerfile.prod
    container_name: react_app_prod
    ports:
      - "80:80"
    restart: unless-stopped